config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'
  get "/home/about" => 'homes#show'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get "search" => "searches#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end





  def self.looks(searches, words)
                if searches == "forward_match"
                        @book = Book.where("title LIKE?","#{words}%")
                elsif searches == "backward_match"
                         @book = Book.where("title LIKE?","%#{words}")
                elsif searches == "perfect_match"
                         @book = Book.where("title LIKE?", "#{words}")
                elsif searches == "partial_match"
                         @book = Book.where("title LIKE?","%#{words}%")
                else
                         @book = Book.all
                end
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comment, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end



  def self.looks(searches, words)
                if searches == "forward_match"
                        @user = User.where("name LIKE ?", "#{words}%")
                elsif searches == "backward_match"
                        @user = User.where("name LIKE ?", "%#{words}")
                elsif searches == "perfect_match"
                        @user = User.where("name LIKE ?", "#{words}")
                elsif searches == "partial_match"
                        @user = User.where("name LIKE ?", "%#{words}%")
                else
                        @user = User.all
                end
  end

  attachment :profile_image

 validates :name, length: { in: 2..20 }, uniqueness: true
validates :introduction, length: { maximum: 50 }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    "/"
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in,keys:[:name])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @user = @book.user
    @books = Book.new
    @book_comment = BookComment.new


    @comment = current_user.book_comment.new(book_params)
    @comment.book_id = @book.id

    if @comment.save

    else

      # render "books/show"
    end
  end

  def destroy
    @book_comment = BookComment.new
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy

  end

  private

  def book_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @books2 = Book.all
    @users = User.all

    @book = Book.new

  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.new
    @book_comment = BookComment.new
  end

  def create
    @user = current_user
    @books2 = Book.all


    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      redirect_to book_path(@book), notice: 'You have created book successfully.'
    else
      render :index
    end
  end


  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


private

def book_params
  params.require(:book).permit(:title, :body)
end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    #binding.pry


  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy



  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


  def top
  end

  def show
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  def create
     current_user.follow(params[:user_id])
    redirect_to request.referer
  end 
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController


  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @users = User.all
    @books = Book.new

  end

  def show
    @user= User.find(params[:id])

    @books1 = @user.books
    @books = Book.new

  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render  :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

private
def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
    <div class="col-md-8 mt-4">
      <table class="table">
        <% book.book_comments.each do |book_comment| %>
        <tbody>
          <tr>
            <td>
            <%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></br>
            <%= link_to user_path(book_comment.user) do %>
              <%= book_comment.user.name %>
            <% end %>
            </td>
            <td>
            <%= book_comment.comment %>
            </td>
            <td>
              <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class:"btn btn-sm btn-danger" %>
              <% end %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
      </div>


      <div class="new-comment ">
        <%= form_with model: [book, book_comment], remote: true do |f| %>
          <%= f.text_area :comment, size: "80x10", placeholder: "コメント" %>
          <%= f.submit "送信" %>
        <% end %>
      </div>

app/views/book_comments/create.js.erb
$("#book_comment").html("<%= j(render 'book_comments/comment', book: @book, book_comment: @book_comment) %>")
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$("#book_comment").html("<%= j(render 'book_comments/comment', book: @book, book_comment: @book_comment ) %>")

app/views/books/edit.html.erb
<%= render '/loginheader' %>

  <% if @book.errors.any? %>
    <%= @book.errors.count %>件のerrorが発生しました
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>

<main>
        <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		  <h1>Editing Book</h1>
        <%= form_with model:@book, local:true do |f| %>
    		  <!--<form action="/books/5077" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="patch"><input type="hidden" name="authenticity_token" value="SHcZ71hW6xaaCctCRS1jPGpEVsLPtyia94rHlOCsuZITu9p953DR4CKLdiG0z8jxQ/pmCRpAQEtSr09Z+bXbBA==">-->
          <div class="form-group">
            <label for="book_title">Title</label>

            <%= f.text_field :title, class:"form-control book_title", autofocus: true, id:"inputTitle" %>
            <!--<input class="form-control book_title" type="text" value="s" name="book[title]" id="book_title">-->
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"form-control book_body", autofocus: true, id:"inputBody" %>
            <!--<textarea class="form-control book_body" name="book[body]" id="book_body">s</textarea>-->
          </div>

          <div class="form-group">
            <%= f.submit "Update Book", class:"btn btn-secondary" %>
            <!--<input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">-->
          </div>
        <% end %>
        <div>
          <%= link_to "Show", book_path(@book) %>
        		<!--<a class="book_5077" href="/books/5077">Show</a> |-->
        		|
        	<%= link_to "Back", books_path %>
        		<!--<a class="back" href="/books">Back</a>-->
        </div>
      </div>
    </div>
  </div>
</main>

<%= render '/footer' %>

app/views/books/index.html.erb
  <%= render '/loginheader' %>

  <% if @book.errors.any? %>
    <%= @book.errors.count %>件のerrorが発生しました
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <%= render '/search' %>


  <%= render '/rightsideber', user: @user, books: @book %>


  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <% @books2.each do |book| %>
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg'%>
              <!--<a href="/users/5467">-->
              <!--<img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg">-->
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
             <p><%= book.title %></p>
            <!--<a class="book_5072" href="/books/5072">リーダブルコード</a>-->
            <% end %>
          </td>
          <td>
            <p><%= book.body %></p>
          <!--より良いコードを書くためのシンプルで実践的なテクニック。-->
          </td>
          <td>
            <div id="books_favorite_<%= book.id %>">
              <%= render 'favorites/favorite', book: book %>
            </div>
          </td>

          <td>
            <p><%= "コメント数: #{book.book_comments.count} " %></p>
          </td>


        </tr>
      </tbody>
      <% end %>
    </table>
  </div>


<%= render '/footer' %>

app/views/books/show.html.erb
<%= render '/loginheader' %>

<main>
  <%= render '/rightsideber', user: @user, books: @books %>

  <div class="col-md-8 offset-md-1">
  	<h2>Book detail</h2>
  	<table class="table">
  		<tbody>
  		  <tr>
          <td>
            <%= link_to user_path(@user) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg'%>
            <% end %>
            </br>
            <%= link_to @user.name, user_path(@user) %>
              <!--<img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg"><br>-->
          </td>
          <td>
            <p><%= @book.title %></p>
          </td>
          <td>
            <p><%= @book.body %></p>
          </td>

          <td>

            <div id="books_favorite_<%= @book.id %>">
              <%= render 'favorites/favorite', book: @book %>
            </div>


          </td>

          <td>
            <% if @user == current_user %>
            <%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %>
            <!--<a class="btn btn-sm btn-success edit_book_5759" href="/books/5759/edit">Edit</a>-->
            <% end %>
          </td>
          <td>
            <% if @user == current_user %>
            <%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-sm btn-danger" %>
            <!--<a data-confirm="本当に消しますか？" class="btn btn-sm btn-danger destroy_book_5759" rel="nofollow" data-method="delete" href="/books/5759">Destroy</a>-->
            <% end %>
          </td>
          <td>
            <p>コメント件数：<%= @book.book_comments.count %></p>
          </td>
        </tr>
      </tbody>
    </table>

    <% if @comment.present? %>
    <div id="error_explanation">
      <h2><%= @comment.errors.count %>件のエラーが発生しました。</h2>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div id = "book_comment">
  <%= render 'book_comments/comment', book: @book, book_comment: @book_comment %>
</div>


  </div>
</main>

<%= render '/footer' %>

app/views/favorites/_favorite.html.erb
 <% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
        ♥<%= book.favorites.count %>
      <% end %>
    </p>
  <% else %>
    <p>
      <%= link_to book_favorites_path(book), method: :post, remote: true do %>
        ♡<%= book.favorites.count %>
      <% end %>
    </p>
  <% end %>

app/views/favorites/create.js.erb
$("#books_favorite_<%= @book.id %>").html("<%= j(render 'favorites/favorite', book: @book ) %>")
<!--$("p").css("color", "red"); -->

app/views/favorites/destroy.js.erb
$("#books_favorite_<%= @book.id %>").html("<%= j(render 'favorites/favorite', book: @book ) %>")

app/views/homes/about.html.erb
<%= render '/header' %>

<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

<%= render '/footer' %>

app/views/homes/show.html.erb
<%= render '/header' %>

<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

<%= render '/footer' %>

app/views/homes/top.html.erb
<% if user_signed_in? %>
  <%= render '/loginheader' %>
<% else %>
  <%= render '/header' %>
<% end %>

  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6 mt-4">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", "/users/sign_in", class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
            <!--<a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>-->
          </div>
          <div class="row">
            <%= link_to "Sign Up", "/users/sign_up", class:"btn btn-success btn-sm btn-block sign_up" %>

          </div>
        </div>
      </div>
    </div>
　</div>

<%= render '/footer' %>

app/views/relationships/followers.html.erb
 <%= render '/loginheader' %>

<main>
  <h1>Follower Users</h1>
</main>
<table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.png", size: '50x50' %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              フォロー数
              <%= user.followings.count %>
            </td>
            <td>
              フォロワー数
              <%= user.followers.count %>
            </td>
            <td>
              <% if current_user.following?(user) %>
                <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
              <% end %>

            </td>
            <td>
              <%= link_to "Show", user_path(user.id)  %>
            <!--<a class="user_5471" href="/users/5471">Show</a>-->
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>


 <%= render '/footer' %>

app/views/relationships/followings.html.erb
 <%= render '/loginheader' %>

<main>
  <h1>Follow Users</h1>
</main>
<table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.png", size: '50x50' %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              フォロー数
              <%= user.followings.count %>
            </td>
            <td>
              フォロワー数
              <%= user.followers.count %>
            </td>
            <td>
              <% if current_user.following?(user) %>
                <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
              <% end %>

            </td>
            <td>
              <%= link_to "Show", user_path(user.id)  %>
            <!--<a class="user_5471" href="/users/5471">Show</a>-->
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>


 <%= render '/footer' %>

app/views/searches/search.html.erb
<%= render '/loginheader' %>

<%= render '/search' %>

<% if @range == "User" %>
<h1>ユーザー検索結果</h1>
<p><%=  params[:word]  %>　検索</p>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <% @users.each do |user| %>
    <tbody>
      <tr>
        <td>
          <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.png", size: '50x50' %>
        </td>
        <td>
          <%= link_to user_path(user) do %>
          <%= user.name %>
          <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>


    <% else %>
    <h1>本タイトル検索結果</h1>
    <p><%=  params[:word]  %>　検索</p>
     <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <% @books.each do |book| %>
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg'%>
              <!--<a href="/users/5467">-->
              <!--<img class="attachment user profile_image fallback" src="/assets/no-image-icon-d3f9e11cb2bb284b42e0810f94b03c50126f51f482ea43054b87c2b7ebaa01d5.jpg">-->
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
             <p><%= book.title %></p>
            <!--<a class="book_5072" href="/books/5072">リーダブルコード</a>-->
            <% end %>
          </td>
          <td>
            <p><%= book.body %></p>
          <!--より良いコードを書くためのシンプルで実践的なテクニック。-->
          </td>
           </tr>
      </tbody>
      <% end %>
    </table>
    <% end %>

    <%= render '/footer' %>

app/views/users/edit.html.erb
<%= render '/loginheader' %>

<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
    <!--<form enctype="multipart/form-data" action="/users/5472" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="patch"><input type="hidden" name="authenticity_token" value="CY5PFfec0fiUXHyAKbJ4Po6LIvqc+OXXr1cz6ZNSPNp3z0LHXXV2g+/NQyO/rziInuyb65qTQpsT5FPCicER9w==">-->

        <% if @user.errors.any? %>
        <%= @user.errors.count %>件のerrorが発生しました</br>
          <% @user.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>



        <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="inputName">Name</label>
          <%= f.text_field :name, class:"form-control name", autofocus: true, id:"inputName", placeholder:"名前"%>
        </div>

        <div class="form-group">
          <label for="inputImage">Image</label>
          <%= f.attachment_field :profile_image, class:"form-control-file user_image", placeholder: "プロフィール画像" %>
        </div>

        <div class="form-group">
          <label for="inputIntroduction">Introduction</label>
          <%= f.text_field :introduction, class:"form-control introduction", autofocus: true, id:"inputIntroduction", placeholder:"紹介文"%>
        </div>

        <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        <!--<input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">-->
        </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

<%= render '/footer' %>

app/views/users/index.html.erb
<%= render '/loginheader' %>

<%= render '/search' %>

  <main>
    <%= render '/rightsideber', user: @user, books: @books %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.png", size: '50x50' %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              フォロー数
              <%= user.followings.count %>
            </td>
            <td>
              フォロワー数
              <%= user.followers.count %>
            </td>
            <td>
              <% if user == current_user %>

              <% else %>
                <% if current_user.following?(user) %>
                  <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                <% end %>
              <% end %>

            </td>
            <td>
              <%= link_to "Show", user_path(user.id)  %>
            <!--<a class="user_5471" href="/users/5471">Show</a>-->
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </main>

  <%= render '/footer' %>

app/views/users/show.html.erb
<%= render '/loginheader' %>

<main>
  <%= render '/rightsideber', user: @user, books: @books %>

  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>

    <% @books1.each do |book| %>
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg'%>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <p><%= book.title %></p>
              <!--<a class="book_5072" href="/books/5072">リーダブルコード</a>-->
            <% end %>
          </td>
          <td>
            <p><%= book.body %></p>
            <!--より良いコードを書くためのシンプルで実践的なテクニック。-->
          </td>
           <td>
            <p><%= "コメント数: #{book.book_comments.count} " %></p>
          </td>
        </tr>
      </tbody>
    <% end %>
    </table>
  </div>
</main>

<%= render '/footer' %>